import type { NextPage } from 'next'
import Head from 'next/head'
import { RandomFox } from '../components/RandomFox'

const random = () => Math.floor(Math.random() * 123) + 1

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Random Fox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col pt-12 items-center">
        <h1 className="text-4xl font-bold">Hola NextJS</h1>
        <RandomFox image={`https://randomfox.ca/images/${random()}.jpg`}/>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
